#!/usr/bin/python3
import sys
import math
def main():
    if len(sys.argv) != 2:
        print("Usage: ./factors input_file")
        sys.exit(1)
    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as file:
            for line in file:
                input_data = int(line.strip())
                root_sqrt = int(math.sqrt(input_data))
                p = input_data
                q = 1
                for i in range(2, root_sqrt + 1):
                    if (input_data % i) == 0:
                        p = i
                        q = input_data // p
                        break
                print(input_data, '=', p, '*', q)
    except FileNotFoundError:
        print("File not found:", input_file)
        sys.exit(1)
if __name__ == "__main__":
    main()
